version: '1.0.{build}'
image: Visual Studio 2017
environment:
  matrix:
  # node.js
    - nodejs_version: "6"
branches:
  only:
  - master
install:
  - ps: Install-Product node $env:nodejs_version
  - IF %nodejs_version% LSS 4 npm -g install npm@2
  - set PATH=%APPDATA%\npm;%PATH%
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: cd ./src
  - cmd: npm install npm -g
  - cmd: npm install
build_script:
  - cmd: dotnet publish -c Release -o .\release\
artifacts:
 - path: 'src\release\'
   name: WebSite
   type: WebDeployPackage
clone_depth: 1
deploy:
- provider: WebDeploy
  server: https://blhackernews.scm.azurewebsites.net:443/msdeploy.axd?site=blhackernews
  website: blhackernews
  NTLM: disabled
  username:
    secure: eJQDUj/eA9MKhOBa0cVT3w==
  password:
    secure: 9rjdN8KcWv2Qt8OVwUY4ndsFgZl2A7Ei/cCPrR2TNbsGsFfX7MBzpD/nroWQiTbW71qeHPgFHGRQSoChvB3sOA==
  artifact: WebSite
  aspnet_core: true
  app_offline: true
  aspnet_core_force_restart: true
